require_relative '../OpenTokSDKVersion'
source 'https://github.com/CocoaPods/Specs.git'

platform :osx, MinMacOSVersion

workspace 'Custom-Audio-Driver.xcworkspace'

target 'Custom-Audio-Driver' do
  project 'Custom-Audio-Driver.xcodeproj'
  use_frameworks! :linkage => :static
  pod 'VonageClientSDKVideoMacOS', OpenTokSDKVersion
end
