require_relative '../OpenTokSDKVersion'
source 'https://github.com/CocoaPods/Specs.git'

platform :osx, MinMacOSVersion

workspace 'Media-Transformers.xcworkspace'

target 'Media-Transformers' do
  project 'Media-Transformers/Media-Transformers.xcodeproj'
  use_frameworks! :linkage => :static
  pod 'VonageClientSDKVideoMacOS', OpenTokSDKVersion
  pod 'VonageClientSDKVideoMacOSTransformers' , OpenTokSDKVersion
end