require_relative '../OpenTokSDKVersion'
source 'https://github.com/CocoaPods/Specs.git'

platform :osx, MinMacOSVersion

workspace 'Video-Transformers.xcworkspace'

target 'Video-Transformers' do
  project 'Video-Transformers/Video-Transformers.xcodeproj'
  use_frameworks! :linkage => :static
  pod 'VonageClientSDKVideoMacOS', OpenTokSDKVersion
  pod 'VonageClientSDKVideoMacOSTransformers' , OpenTokSDKVersion
end