require_relative '../OpenTokSDKVersion'
source 'https://github.com/CocoaPods/Specs.git'

platform :osx, MinMacOSVersion

workspace 'Basic-Video-Chat.xcworkspace'

target 'Basic-Video-Chat' do
  project 'Basic-Video-Chat/Basic-Video-Chat.xcodeproj'
  use_frameworks! :linkage => :static
  pod 'VonageClientSDKVideoMacOS', OpenTokSDKVersion
end